# Generated by Django 2.1.3 on 2019-01-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='autotrigger_enable',
            field=models.BooleanField(default=False, verbose_name='enable AutoTrigger'),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='autotrigger_sexdatingdiscordbots_score',
            field=models.FloatField(default=10, help_text='Set to 0 to disable', verbose_name='message looks like a link spam for a "Sex Dating" scam website '),
        ),
    ]
