# Generated by Django 2.1.7 on 2019-03-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_auto_20190116_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('ban', 'Ban'), ('unban', 'Unban'), ('softban', 'Softban'), ('kick', 'Kick'), ('warn', 'Warn'), ('note', 'Note'), ('mute', 'Mute'), ('unmute', 'Unmute')], max_length=15),
        ),
    ]
