# Generated by Django 2.1.7 on 2019-03-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0004_auto_20190318_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='thresholds_mutes_to_kick',
            field=models.IntegerField(default=2, verbose_name='number of mutes that must be applied to a user before they receive an automatic kick'),
        ),
    ]
