# Generated by Django 2.1.3 on 2018-11-11 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ban', 'Ban'), ('unban', 'Unban'), ('kick', 'Kick'), ('warn', 'Warn'), ('note', 'Note')], max_length=15)),
                ('reason', models.CharField(max_length=5000, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('discord_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('discord_name', models.CharField(max_length=200)),
                ('discord_icon_url', models.URLField()),
                ('discord_created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('discord_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('discord_name', models.CharField(max_length=200)),
                ('discord_discriminator', models.IntegerField()),
                ('discord_avatar_url', models.URLField()),
                ('discord_default_avatar_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='discordguild',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='guilds_owned', to='webinterface.DiscordUser'),
        ),
        migrations.AddField(
            model_name='action',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='webinterface.DiscordGuild'),
        ),
        migrations.AddField(
            model_name='action',
            name='responsible_moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions_given', to='webinterface.DiscordUser'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions_received', to='webinterface.DiscordUser'),
        ),
    ]
