# Generated by Django 2.1.3 on 2018-11-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordguild',
            name='discord_user_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
