# Generated by Django 2.1.3 on 2018-11-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0002_discordguild_discord_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('ban', 'Ban'), ('unban', 'Unban'), ('softban', 'Softban'), ('kick', 'Kick'), ('warn', 'Warn'), ('note', 'Note')], max_length=15),
        ),
    ]
