# Generated by Django 2.1.3 on 2018-11-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_auto_20181111_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='attachement',
            field=models.URLField(null=True),
        ),
    ]
