# Generated by Django 2.1.3 on 2018-11-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0004_action_attachement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='attachement',
            new_name='attachments',
        ),
    ]
