# Generated by Django 2.1.3 on 2018-11-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0005_auto_20181111_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
