# Generated by Django 2.1.3 on 2018-11-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0006_auto_20181111_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='attachment',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
