# Generated by Django 2.1.3 on 2018-11-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0007_auto_20181111_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='reason',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
