# Generated by Django 2.1.3 on 2018-11-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0009_apiaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordguild',
            name='discord_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='discord_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
