# Generated by Django 2.1.3 on 2018-11-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0014_auto_20181113_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='tresholds_enable',
            field=models.BooleanField(default=False, verbose_name='enable tresholds'),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='tresholds_kicks_to_bans',
            field=models.IntegerField(default=3, verbose_name='number of kicks that must be applied to a user before they receive an automatic ban'),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='tresholds_softbans_to_bans',
            field=models.IntegerField(default=2, verbose_name='number of softbans that must be applied to a user before they receive an automatic ban'),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='tresholds_warns_to_kick',
            field=models.IntegerField(default=3, verbose_name='number of warns that must be applied to a user before they receive an automatic kick'),
        ),
    ]
