# Generated by Django 2.1.3 on 2018-11-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0015_auto_20181113_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='automod_logs',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
