# Generated by Django 2.1.3 on 2018-11-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0016_action_automod_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='logs_channel_id',
            field=models.BigIntegerField(default=0, verbose_name='ID of the channel to log messages to.'),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='logs_enable',
            field=models.BooleanField(default=False, verbose_name='enable logging actions to a channel'),
        ),
    ]
