# Generated by Django 2.1.3 on 2018-11-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0018_auto_20181119_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='automod_ignore_invites_in',
            field=models.BigIntegerField(default=0, verbose_name='channel id where the bot will ignore untrusted invites (set to 0 to disable)'),
        ),
    ]
