# Generated by Django 2.1.3 on 2018-11-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0019_guildsettings_automod_ignore_invites_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='automod_minimal_membercount_trust_server',
            field=models.IntegerField(default=10000, verbose_name='Minimum member count to consider a server trusted. (set to 0 to disable trusting server using member count)'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_score_bad_words',
            field=models.FloatField(default=0.15, verbose_name='message conatins bad_words (score added for every bad word)'),
        ),
    ]
