# Generated by Django 2.1.3 on 2018-11-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0020_auto_20181119_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-id']},
        ),
    ]
