# Generated by Django 2.1.3 on 2018-11-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0021_auto_20181120_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildsettings',
            name='logs_channel_id',
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='logs_moderation_channel_id',
            field=models.BigIntegerField(default=0, verbose_name='ID of the channel to log messages to. (set to 0 to disable logging for this)'),
        ),
    ]
