# Generated by Django 2.1.3 on 2018-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0022_auto_20181120_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='logs_delete_channel_id',
            field=models.BigIntegerField(default=0, verbose_name='ID of the channel to log messages delete to'),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='logs_edits_channel_id',
            field=models.BigIntegerField(default=0, verbose_name='ID of the channel to log messages edits to'),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='logs_joins_channel_id',
            field=models.BigIntegerField(default=0, verbose_name='ID of the channel to log joins and leave to'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='logs_enable',
            field=models.BooleanField(default=False, verbose_name='enable logging actions to a channel (set an ID to 0 to disable logging for the specific log)'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='logs_moderation_channel_id',
            field=models.BigIntegerField(default=0, verbose_name='ID of the channel to log moderation messages to'),
        ),
    ]
