# Generated by Django 2.1.3 on 2018-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0023_auto_20181120_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='imported_bans',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
