# Generated by Django 2.1.3 on 2018-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0025_auto_20181120_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='logs_as_embed',
            field=models.BooleanField(default=True, verbose_name='use cooler embeds in logs (disable to use plain text)'),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='logs_member_edits_channel_id',
            field=models.BigIntegerField(default=0, verbose_name='ID of the channel to log members name changes to'),
        ),
    ]
