# Generated by Django 2.1.3 on 2018-12-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0026_auto_20181122_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='admin_info',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='discord_bot',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_ban_score',
            field=models.FloatField(default=10, help_text='Set to 0 to disable', verbose_name='automod score to ban the author of a message'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_delete_message_score',
            field=models.FloatField(default=1.5, help_text='Set to 0 to disable', verbose_name='automod score to delete messages'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_ignore_invites_in',
            field=models.BigIntegerField(default=0, help_text='Set to 0 to disable ignoring invites in a channel', verbose_name='channel id where the bot will ignore untrusted invites'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_ignore_level',
            field=models.IntegerField(default=2, help_text='Level 2 is trusted users, 3 moderators, 4 admins and 5 owner.', verbose_name='minimum bot level required for automod to ignore you'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_kick_score',
            field=models.FloatField(default=0, help_text='Set to 0 to disable', verbose_name='automod score to kick the author of a message'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_minimal_membercount_trust_server',
            field=models.IntegerField(default=10000, help_text='Set to 0 to disable trusting servers using their member count', verbose_name='Minimum member count to consider a server trusted'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_multiplictor_bot_banned',
            field=models.FloatField(default=0.25, help_text='You can bot-ban people with +add_banned [user] in your server', verbose_name='message author is banned from the bot'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_multiplictor_have_nitro',
            field=models.FloatField(default=-0.75, help_text='Due to discord limitations, only nitro users with animated avatars are currently detected.', verbose_name='message author has nitro'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_multiplictor_have_roles',
            field=models.FloatField(default=-0.1, verbose_name='message author have more than one role in the server'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_multiplictor_just_joined',
            field=models.FloatField(default=0.5, help_text='Was in the server for less than a day since the last join', verbose_name='message author just joined the server'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_multiplictor_new_account',
            field=models.FloatField(default=0.75, help_text='Account less than a week old', verbose_name='message author account is new'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_multiplictor_offline',
            field=models.FloatField(default=0.15, help_text='Most spammers use(d) invisible mode to be harder to mention when banning', verbose_name='message author is offline'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_score_bad_words',
            field=models.FloatField(default=0.15, help_text='This score is added for each bad word found in the message. Note that this is imperfect and subject to change', verbose_name='message contains bad words'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_score_caps',
            field=models.FloatField(default=1, help_text='To prevent messages like "OK" to be flagged as full-caps, messages must be at least 16 chars in length, and shoudn\'t look like a command (experimental)', verbose_name='message written in CAPS LOCK'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_score_contain_invites',
            field=models.FloatField(default=2.5, help_text="Untrusted invites are invites for another server that the one they are in, with a member count smaller than what's specified in the misc options of the automod", verbose_name='message contain untrusted invites'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_score_embed',
            field=models.FloatField(default=5, help_text='Rich embeds cannot be sent by users without using a userbot. They are often used to circumvent the message filtering', verbose_name='message contain a rich embed'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_score_everyone',
            field=models.FloatField(default=1, help_text='Note that this will only be true if the @everyone ping failed', verbose_name='message contain a failed @everyone ping'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_score_repeated',
            field=models.FloatField(default=0.25, help_text="This score is added for every repeat (so, if I sent the same message 4 times, that'd be 4*0.25=1)", verbose_name='message was repeated more than 3 times'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_score_too_many_mentions',
            field=models.FloatField(default=1, help_text='More than 3 of them', verbose_name='message contain too many user mentions'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_softban_score',
            field=models.FloatField(default=7, help_text='Set to 0 to disable', verbose_name='automod score to softban the author of a message'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_warn_score',
            field=models.FloatField(default=2, help_text='Set to 0 to disable', verbose_name='automod score to warn the author of a message'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='bot_prefix',
            field=models.CharField(default='+', help_text='The g+ prefix will always work, regardless of this setting', max_length=15, verbose_name='bot prefix'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='logs_as_embed',
            field=models.BooleanField(default=True, help_text='Disable to use plain text', verbose_name='use cooler embeds in logs'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='logs_enable',
            field=models.BooleanField(default=False, help_text='Set a specific log channel ID to 0 to disable that particular log', verbose_name='enable logging actions to a channel'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='permissions_admins',
            field=models.ManyToManyField(blank=True, help_text='Select multiple users with CTRL+click. Add users with +add_admin [user] in your server', related_name='admin_status', to='webinterface.DiscordUser', verbose_name='additional admins'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='permissions_banned',
            field=models.ManyToManyField(blank=True, help_text='Select multiple users with CTRL+click. Add users with +add_banned [user] in your server', related_name='banned_status', to='webinterface.DiscordUser', verbose_name='additional banned users'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='permissions_moderators',
            field=models.ManyToManyField(blank=True, help_text='Select multiple users with CTRL+click. Add users with +add_moderator [user] in your server', related_name='moderator_status', to='webinterface.DiscordUser', verbose_name='additional moderators'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='permissions_trusted',
            field=models.ManyToManyField(blank=True, help_text='Select multiple users with CTRL+click. Add users with +add_trusted [user] in your server', related_name='trusted_status', to='webinterface.DiscordUser', verbose_name='additional trusted users'),
        ),
    ]
