# Generated by Django 2.1.3 on 2018-12-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0027_auto_20181208_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='using_dark_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='admin_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
