# Generated by Django 2.1.3 on 2018-12-15 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0028_auto_20181214_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_beta_features', models.BooleanField(default=False)),
                ('dark_theme_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='using_dark_theme',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_settings', to='webinterface.DiscordUser'),
        ),
    ]
