# Generated by Django 2.1.3 on 2018-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0029_auto_20181215_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordguild',
            name='discord_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='discord_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='automod_ignore_invites_in',
            field=models.CharField(default=0, help_text='Set to 0 to disable ignoring invites in a channel', max_length=40, verbose_name='channel id where the bot will ignore untrusted invites'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='logs_delete_channel_id',
            field=models.CharField(default=0, max_length=40, verbose_name='ID of the channel to log messages delete to'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='logs_edits_channel_id',
            field=models.CharField(default=0, max_length=40, verbose_name='ID of the channel to log messages edits to'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='logs_joins_channel_id',
            field=models.CharField(default=0, max_length=40, verbose_name='ID of the channel to log joins and leave to'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='logs_member_edits_channel_id',
            field=models.CharField(default=0, max_length=40, verbose_name='ID of the channel to log members name changes to'),
        ),
        migrations.AlterField(
            model_name='guildsettings',
            name='logs_moderation_channel_id',
            field=models.CharField(default=0, max_length=40, verbose_name='ID of the channel to log moderation messages to'),
        ),
    ]
